project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis Notebooks"
  navbar:
    # left:
    #   - href: index.qmd
    #     text: Home
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/esg_text_mining_poc_final.ipynb
        text: Company Ethical Check

format:
  html:
    theme: cosmo
    toc: true



