project:
  type: website

output-dir: _site

theme: cosmo

website:
  title: "Data Analysis Projects"

  navbar:

    right:
      - icon: "github"
        href: "https://github.com/eamonnk"
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/esg_text_mining_poc_final.ipynb
        text: Eticheck
      - href: notebooks/exoplanet_id_clustering_final.ipynb
        text: exoplanet ID

format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    link-citations: true
    lang: en
    date-format: long




