project:
  type: website
  # output-dir: docs

website:
  title: "Data Analysis Projects"
  output-dir: "_posts"
  navbar:
    # left:
    #   - href: index.qmd
    #     text: Home
    right:
      - icon: "github"
        href: "https://github.com/eamonnk"
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/esg_text_mining_poc_final.ipynb
        text: Eticheck
      - href: notebooks/exoplanet_id_clustering_final.ipynb
        text: exoplanet ID
  theme: cosmo
  blog:
    output-dir: "_posts"
    title: "ek-blog"
    description: "Data analysis and commentary"
    date-format: long
    lang: en
    link-citations: true
    document-css: false



